# Broker sécurisé — SMART-FISHING
# Port 8883, TLS 1.2, authentification obligatoire

listener 8883
cafile /etc/mosquitto/ca.crt
certfile /etc/mosquitto/server.crt
keyfile /etc/mosquitto/server.key
tls_version tlsv1.2

allow_anonymous false
password_file /etc/mosquitto/passwd
persistence false
