# Broker sécurisé — SMART-FISHING
# Port 8883, TLS 1.2, authentification obligatoire

listener 8883
cafile /home/tva05/SMART-FISHING/certs/ca.crt
certfile /home/tva05/SMART-FISHING/certs/server.crt
keyfile /home/tva05/SMART-FISHING/certs/server.key
tls_version tlsv1.2

allow_anonymous false
persistence false

password_file /home/tva05/SMART-FISHING/conf/passwd
